name: sdgp_test01
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  outline_gradient_button: ^2.0.1+1
  shared_preferences: ^2.0.6
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  flutter_svg_provider: ^1.0.4
  intl: ^0.19.0
  image_picker: ^1.0.5
  carousel_slider: ^4.0.0
  http: ^1.2.1
  firebase_storage: ^11.6.7
  firebase_core: ^2.27.0
  rename_app: ^1.3.2
  # cloud_firestore: ^4.15.7


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeueBold.ttf
